import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Oswald } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
  weight: ["400", "700"], // You can customize weights
  subsets: ["latin"], // Subset options (latin, latin-ext, etc.)
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
